name: Build and deploy container app to Azure Web App - mywebappv2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pythonappsregistry.azurecr.io/
        username: ${{ secrets.AZURE_CONTAINER_CLIENT_ID }}
        password: ${{ secrets.AZURE_CONTAINER_CLIENT_SECRET }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: pythonappsregistry.azurecr.io/${{ secrets.AZURE_CONTAINER_CLIENT_ID }}/samples/todolist-app:${{ github.sha }}
        file: ./Dockerfile