name: Build and deploy python container app to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  # Container registry service connection established during pipeline creation
  azureContainerRegistry: 'pythonappsregistry.azurecr.io'
  # Web app name
  webAppName: 'mycontainersampleapp'
  # Resource group
  resourceGroupName: 'article'
  # Image name
  imageName: 'todolist-app'
  # FQDN
  fqdn: 'mycontainersampleapp.azurewebsites.net'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://$azureContainerRegistry/
        username: ${{ secrets.AZURE_CONTAINER_CLIENT_ID }}
        password: ${{ secrets.AZURE_CONTAINER_CLIENT_SECRET }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: $azureContainerRegistry/builds/todolist-app:${{ github.sha }}
        file: ./Dockerfile
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIAL }}

    - name: 'Allow basic publishing credentials access'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az resource update --resource-group article --name scm --namespace Microsoft.Web \
          --resource-type basicPublishingCredentialsPolicies --parent sites/$webAppName \
          --set properties.allow=true

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '$webAppName'
        slot-name: 'production'
        publish-profile: ${{ secrets.MYCONTAINERSAMPLEAPP_PUBLISH_PROFILE }}
        images: '$azureContainerRegistry/builds/todolist-app:${{ github.sha }}'